default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projekt_hotel_development
  pool: 5
  username: projekt_hotel
  password: password1

test:
  <<: *default
  database: projekt_hotel_test
  pool: 5
  username: projekt_hotel
  password: password1

production:
  <<: *default
  database: projekt_hotel_production
  username: projekt_hotel
  password: <%= ENV['PROJEKT_HOTEL_DATABASE_PASSWORD'] %>
